application: 'happymeteo'
runtime: java7
version: 'mobile-1373439333'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
admin_console:
  pages:
  - name: Mobile Backend settings
    url: /admin/configure.jsp
api_version: '1.0'
handlers:
- url: (/admin/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/admin/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/admin/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/admin)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /admin/
  script: unused
  login: admin
  secure: optional
- url: /admin/.*/
  script: unused
  login: admin
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /admin/.*\.jsp
  script: unused
  login: admin
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /admin/cconf
  script: unused
  login: admin
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /_ah/spi/.*
  script: unused
  login: optional
  secure: optional
